#include<stdio.h>
#include<conio.h>
void main()
{
int n,i,j;
clrscr();
printf("enter the table number= ");
scanf("%d",&n);
if(n==1)
{  for(i=1;i<=10;i++)
{
printf("   %d*%d=%d  ",n,i,n*i);
}
}
else if(n==2)
{  for(i=1;i<=10;i++)
{
printf("%d*%d= %d  ",n,i,n*i);
}
}
else if(n==3)
{  for(i=1;i<=10;i++)
{
printf("%d*%d=%d  ",n,i,n*i);
}
}
else if(n==4)
{  for(i=1;i<=10;i++)
{
printf("%d*%d=%d  ",n,i,n*i);
}
}
else if(n==5)
{  for(i=1;i<=10;i++)
{
printf("%d*%d=%d  ",n,i,n*i);
}
}
else if(n==6)
{  for(i=1;i<=10;i++)
{
printf("%d*%d=%d  ",n,i,n*i);
}
}
else if(n==7)
{  for(i=1;i<=10;i++)
{
printf("%d*%d=%d  ",n,i,n*i);
}
}
else if(n==8)
{  for(i=1;i<=10;i++)
{
printf("%d*%d=%d  ",n,i,n*i);
}
}
else if(n==9)
{  for(i=1;i<=10;i++)
{
printf("%d*%d=%d  ",n,i,n*i);
}
}
else if(n==10)
{  for(i=1;i<=10;i++)
{
printf("%d*%d=%d  ",n,i,n*i);
}
}
else
{
printf("not valid");
}
getch();
}